### ISSUE TITLE
 improvement of follow function

### ISSUE THREAD

**Issue by filipwojnicki** [yatsenkolesh/instagram-nodejs#21]
File: Instagram.js
Method: Follow()

Change headers in fetch from built-in to this.getHeaders().

Line 244: 
`'headers': headers`
change to
`'headers': this.getHeaders()//headers`

This change help me to repair this method. It's work fine now.

**Comment by yatsenkolesh** [comment]
Hello, thank you. You are can to make pull request.

**Comment by filipwojnicki** [comment]
I was trying but i had a problem with it , sorry. Finally, I wrote it on issues, because i had a problem with it

**Comment by yatsenkolesh** [comment]
What is problems you have, when trying to create pull request ? I can help you :)

**Comment by filipwojnicki** [comment]
I think i do this, sorry for problem. Can u look if everything is good ?

**Comment by yatsenkolesh** [comment]
Yeap

**Comment by yatsenkolesh** [comment]
Resolved.
