### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by gnoejuan** [yatsenkolesh/instagram-nodejs#25]
![image](https://user-images.githubusercontent.com/4656027/38774075-80ff46ea-4024-11e8-863b-e06a29138b7e.png)

**Comment by yatsenkolesh** [comment]
Hello. Instagram closed this method for get data within last privacy program, but I know a other way to get same data. When I will have time I will fix this.

**Comment by yatsenkolesh** [comment]
already fixed in 0.3.0
