### ISSUE TITLE
(node:23894) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by roysG** [yatsenkolesh/instagram-nodejs#8]

**Comment by yatsenkolesh** [comment]
Thank you for the issue. Have you solved this problem with html ? When Instagram returned HTML - this is a problem with auth. 

I publish on npm new version of the library with resolved problem an unnecessary library "timeout-as-promise".

If you want to make faster develop of this library - star repository, please. Thank you.

**Comment by roysG** [comment]
Yes, i success to solve this problem, with install the plugin you mention.
But also this error happened to me cause i forget to put all the important fields.

**Comment by yatsenkolesh** [comment]
Ok, thank you.
